### ISSUE TITLE
[bug] Unable to add Nvidia GPU OSS drivers

### ISSUE THREAD

**Issue by sjdrc** [siderolabs/omni-feedback#1]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have been trying to follow this page: https://www.talos.dev/v1.3/talos-guides/configuration/nvidia-gpu/

I created a config patch for my cluster, and pasted in the json configuration patch, but validation failed. I converted it into a strategic merge patch:

```
machine:
  install:
    extensions:
      - image: ghcr.io/siderolabs/nvidia-open-gpu-kernel-modules:515.65.01-v1.3.4
      - image: ghcr.io/siderolabs/nvidia-container-toolkit:515.65.01-v1.11.0
  kernel:
    modules:
      - name: nvidia
      - name: nvidia_uvm
      - name: nvidia_drm
      - name: nvidia_modeset
  sysctls:
    net.core.bpf_jit_harden: 1
```

However I have the following in my logs:
```
user: warning: [2023-02-17T08:27:45.39064125Z]: [talos] controller failed {"component": "controller-runtime", "controller": "runtime.KernelModuleSpecController", "error": "error loading module \x5c"nvidia\x5c": module not found"}
```

Following the rest of the tutorial, I hit an error on the device plugin saying:
```
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "nvidia" is configured
```

### Expected Behavior

GPU operations work

### Steps To Reproduce

See above
