### ISSUE TITLE
[bug] Overwhelming wordpress:apache pod with connections results in the host hanging & network timeouts - rcu_preempt detected stalls on CPUs/tasks

### ISSUE THREAD

**Issue by gerhard** [siderolabs/omni-feedback#41]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If a pod triggers the OOM, Talos OS v1.4.0 hangs.

Connectivity to kube-api-serve is lost (workloads run on control plane) and `eth0` starts getting blocked. The pod is never restarted, but the process inside is definitely killed.

See the attached machine log: [4c4c4544-0042-4610-8033-b4c04f4a3432_omni-1.4.0.log](https://github.com/siderolabs/omni-feedback/files/11361791/4c4c4544-0042-4610-8033-b4c04f4a3432_omni-1.4.0.log)

### Expected Behavior

Pods that trigger the OOM killer should not make the system unstable.

### Steps To Reproduce

I have deployed `wordpress:6.2-apache` with a mem request & limit of `256Mi`.

Benchmarking with [`wrk`](https://github.com/wg/wrk) will trigger this issue in ~10 seconds.

**Comment by smira** [comment]
Can you please provide a deployment which reproduces the problem? 

The `rcu_preempt detected stalls` message is usually related to CPU starvation. The OOM killer should follow the cgroup memory limit which is correctly enforced. CPU starvation might be related to the workload, or a buggy/misconfigured hypervisor (if any)

**Comment by gerhard** [comment]
This bug was initially triggered on a bare-metal host, Dell R220:
![image](https://user-images.githubusercontent.com/3342/235457390-e7929a3b-824b-45d5-b309-52f7fa70f92f.png)

I was able to reproduce it on my experimental bare metal host just now:
![image](https://user-images.githubusercontent.com/3342/235457468-5b788cd3-9bfb-42db-85f9-b4dab4414947.png)

Once a pod enters an OOM loop, the host appears to get overloaded handling the OOMs. `kube-controller-manager`, `kube-scheduler` & `metrics-server` start `CrashLoopBackOff`. 30 minutes later they continue this `CrashLoopBackOff` pattern:
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/3342/235457551-bf7030a6-bc3a-42c9-aac1-bcfde6199c23.png">

K8s connectivity via `*.kubernetes.omni.siderolabs.io` is also affected. It drops and it comes back.

ICMP to the host is also showing increased latency:
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/3342/235458549-1df0ac3f-5612-4693-bb35-e797c341fc56.png">

Even processes running in pods on the host are affected. I have noticed a bunch of `getaddrinfo EAI_AGAIN` errors.

Whatever that repeated OOM triggers seems to have a cascading effect across all subsystems on the host.

I was able to trigger the OOM loop by running: `wrk -t12 -c400 -d60s https://oom-host-hang.gerhard.io/wp-admin/install.php`

I am attaching the output of `omnictl machine-logs 77902500-68a6-0706-0025-9077a6680e0f --follow | tee 77902500-68a6-0706-0025-9077a6680e0f.log`:  [77902500-68a6-0706-0025-9077a6680e0f.log](https://github.com/siderolabs/omni-feedback/files/11365514/77902500-68a6-0706-0025-9077a6680e0f.log)

This contains everything that you need to reproduce the exact workload that triggered the above described state:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: oom-host-hang
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: oom-host-hang
  labels:
    app: wordpress
    type: app
spec:
  selector:
    matchLabels:
      app: wordpress
      type: app
  template:
    metadata:
      labels:
        app: wordpress
        type: app
    spec:
      containers:
      # https://hub.docker.com/_/wordpress
      - image: wordpress:6.2-apache
        name: wordpress
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          # 💥 https://github.com/siderolabs/omni-feedback/issues/41
          limits:
            memory: "256Mi"
        env:
        - name: WORDPRESS_DB_HOST
          value: mariadb
        - name: WORDPRESS_DB_USER
          value: wordpress
        - name: WORDPRESS_DB_PASSWORD
          value: wordpress
        - name: WORDPRESS_DB_NAME
          value: wordpress
        - name: WORDPRESS_DEBUG
          value: "1"
        ports:
        - containerPort: 80
          name: http
      # I am leaving this out so that you do not need to worry about csi-lvm-driver
      #
      #   volumeMounts:
      #   - name: wordpress
      #     mountPath: /var/www/html
      # volumes:
      # - name: wordpress
      #   persistentVolumeClaim:
      #     claimName: wordpress
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: oom-host-hang
  labels:
    app: wordpress
    type: app
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: wordpress
    type: app
  clusterIP: None
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress
  namespace: oom-host-hang
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  rules:
  - host: oom-host-hang.gerhard.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wordpress
            port:
              number: 80
  tls:
    - hosts:
        - oom-host-hang.gerhard.io
      secretName: wordpress-tls
  ingressClassName: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: oom-host-hang
  labels:
    app: mysql
    type: db
spec:
  selector:
    matchLabels:
      app: mysql
      type: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        type: db
    spec:
      containers:
      # https://hub.docker.com/_/mariadb
      - image: mariadb:10.7
        name: mariadb
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          # 💥 https://github.com/siderolabs/omni-feedback/issues/41
          limits:
            memory: "512Mi"
        env:
        - name: MARIADB_DATABASE
          value: wordpress
        - name: MARIADB_USER
          value: wordpress
        - name: MARIADB_PASSWORD
          value: wordpress
        - name: MARIADB_ROOT_PASSWORD
          value: root
        ports:
        - containerPort: 3306
          name: mysql
      # I am leaving this out so that you do not need to worry about csi-lvm-driver
      #
      #   volumeMounts:
      #   - name: mariadb
      #     mountPath: /var/lib/mysql
      # volumes:
      # - name: mariadb
      #   persistentVolumeClaim:
      #     claimName: mariadb
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: oom-host-hang
  labels:
    app: mysql
    type: db
spec:
  ports:
    - name: mysql
      port: 3306
  selector:
    app: mysql
    type: db
  clusterIP: None
```

The ingress is important, otherwise port forwarding will stop working when the pod enters the OOM loop. I have installed ingress-nginx via:

```console
helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx

# helm search repo ingress-nginx/ingress-nginx --versions
export INGRESS_NGINX_VERSION=4.6.0

helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
  --namespace ingress-nginx \
  --version $INGRESS_NGINX_VERSION \
  --set controller.dnsPolicy=ClusterFirstWithHostNet \
  --set controller.hostNetwork=true \
  --set controller.kind=DaemonSet \
  --set controller.service.enabled=false \
  --set controller.publishService.enabled=false
```

---

FWIW, only manually deleting the `wordpress-*` pod in the `oom-host-hang` namespace restored the network connectivity to the pod.

**Comment by smira** [comment]
So I was able to reproduce this case, but I don't see any behavior which is not expected.

Wordpress seems to deploy Apache with a model of fork-per-connection without any limits set. 

I wasn't able to use `wrk` as it seems to be completely broken, but the setting `-c 400` should keep 400 connections, so 400 copies of Apache process. They might fit into cgroup limit, as Linux does copy-on-write strategy. Once they start handling requests, it grows beyond the limit, and OOM killer starts killing processes with highest memory usage (workers). At the same time Apache keeps forking more children, `nginx` ingress has many more requests pending, it keeps feeding Apache with more requests, Apache forks more, oom-killer kills more, etc. In the end kernel has very high CPU usage due to OOM killer fighting with Apache and the load.

The memory limits are enforced correctly. The Apache is misconfigured - it should have a sane limit on max number of workers, better not to use Apache here at all.

The other issues you're seeing are related to the fact that system time is high while OOM killer is running, so other kernel activities are impacted. But `kube-apiserver` and other controlplane components are not affected.

**Comment by gerhard** [comment]
If a pod uses more memory than it is allowed & it keeps getting OOM killed, this should not impact the host. This should especially not impact the control plane, or the host's network.

I could try a few things:
- re-create the experiment with CPU limits
- simulate a pod exceeding its memory limit without involving networking
- show how a managed K8s behaves in this scenario - all the ones that I have experienced do not result in nodes stalling when pods get OOM killed

Would any of the above be helpful?

My assumption is that a resilient OS should be able to OOM a pod without anything else being affected, even if this is due to network overload. I could improve the Apache config, switch to nginx-fpm, limit connections on ingress-nginx, etc. None of this is going to have the desired outcome if a pod OOM will make the entire node unstable.

---
High-level perspective: I want to be able to vouch for Talos in production. If it helps, I am up to pair-up on this. I suspect that we are likely to find a resolution quicker than if we continue with back-and-forth comments.

**Comment by smira** [comment]
I don't think the memory limit doesn't work. In fact all memory limits are applied down to the Linux kernel via cgroups, so OS itself (any OS, whether it's Talos Linux or Ubuntu) doesn't do anything specifically to handle that. 

Kubernetes doesn't recommend running workloads on control plane nodes - there are two reasons - one is security, another is exactly resource starvation.

There are many resources which don't have any limits applied by default, so one could imagine a resource exhaustion scenario pretty easily.

If you want to isolate a "bad" workload, VM isolation is much better way, see `kubevirt`.

**Comment by smira** [comment]
Also you can take a look at the https://sysctl-explorer.net/vm/oom_kill_allocating_task/ setting.

**Comment by smira** [comment]
Setting CPU limits makes things less disturbing, there's plenty of CPU time left idle:

![image](https://user-images.githubusercontent.com/55211/235490292-90818f6e-6dc9-43dc-a69d-844e91d27bf7.png)

**Comment by smira** [comment]
Please feel free to re-open if there's anything new.

**Comment by gerhard** [comment]
The memory limit works. My problem is the impact on the host itself.

I have a few follow-up questions:
- How can I access the machine dashboard view for machines managed by Omni?
- How do I configure & then check the `vm.oom_kill_allocating_task` value on a Talos OS host?

Thank you!

**Comment by smira** [comment]
`talosctl dashboard` should work same way for Omni machines, just use `talosconfig` from Omni.

sysctl values are configured via machine config, so a config patch in Omni: https://www.talos.dev/v1.4/reference/configuration/#machineconfig

```yaml
machine:
  sysctls:
    vm.oom_kill_allocating_task: "1"
```

**Comment by gerhard** [comment]
That was helpful, thank you.

Even with the CPU limit set to `1` & `vm.oom_kill_allocating_task: "1"`, the load went crazy - `69` at one point - and the pod was not killed when it hit the memory limit.

Pods in the `kube-system` namespace which should not be killed were, and everything slowed down to a crawl. Manually killing the pod brought the system load down and a few minutes later everything started working as expected.

<img width="1440" alt="Screenshot 2023-05-01 at 20 33 24" src="https://user-images.githubusercontent.com/3342/235636165-b6e243e2-d633-4db4-9a98-ea54e0d36da3.png">

The fix which worked best was to throttle via ingress:

```yaml
    # https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#rate-limiting
    nginx.ingress.kubernetes.io/limit-connections: "5"
    nginx.ingress.kubernetes.io/limit-rps: "5"
```

This prevents the pod hitting high memory usage and putting too much load on the system. Further tuning will be required, but this solves my immediate problem. I will keep thinking about separating the control plane from the worker nodes. For now, this is the most pragmatic solution.

Thanks @smira for helping out with this.
