### ISSUE TITLE
[feature] Configure etcd backups in the cluster config

### ISSUE THREAD

**Issue by gerhard** [siderolabs/omni-feedback#71]
### Problem Description

etcd backup should be part of the cluster configuration - patch works!

I can definitely see each cluster getting its own credential & maybe even its own S3-compatible bucket.

From a UI perspective, these backups appear at the cluster level, not the global one.

In the big scheme of things, this is a nit-pick - I love the feature!

### Solution

```yaml
kind: Cluster
name: production-2023-12-16
kubernetes:
  version: v1.28.4
talos:
  version: v1.5.5
features:
  backupConfiguration:
    interval: 24h
    bucket: omni-cluster-backups-2023-12-11
    region: eu-west-1
    endpoint: https://s3.dualstack.eu-west-1.amazonaws.com
    accesskeyid: <YOUR_ACCESS_KEY_ID>
    secretaccesskey: <YOUR_SECRET_ACCESS_KEY>
```

### Notes

Discussed with @Unix4ever on #omni Slack: https://taloscommunity.slack.com/archives/C04D4PDAJT0/p1702382041160049?thread_ts=1702239530.277439&cid=C04D4PDAJT0
